export const ROUTES = {
  Drawer: {
    HOME: 'HOME',
    PROFILE: 'PROFILE',
  },
  BOTTOM_TAB: {
    MOVIES: 'MOVIES',
    FAVOURITES: 'FAVOURITES',
  },
  MOVIES_STACK_SCREEN: {
    MOVIES_SCREEN: 'MOVIES_SCREEN',
    MOVIE_DETAILS: 'MOVIE_DETAILS',
    SEARCH_SCREEN: 'SEARCH_SCREEN',
    MODAL_SCREEN: 'MODAL_SCREEN',
  },
} as const;
